name: Release
on:
  workflow_dispatch:
    inputs:
      MESSAGE:
        description: 'message for release body'

  push:
    tags:
    - '*'

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    # get version from manifest.json
    - uses: actions/github-script@v3
      id: get-version
      with:
        result-encoding: string
        script: |
          const fs = require('fs')
          const manifest = JSON.parse(fs.readFileSync('manifest.json'))
          return 'v' + manifest.version

    - name: generate rules
      run: |
        node ./config.js
    
    - name: package files
      run: |
        zip -q "${{ steps.get-version.outputs.result }}.zip" bg.js manifest.json rules.json
        ls -l
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ steps.get-version.outputs.result }}.zip
        tag_name: ${{ steps.get-version.outputs.result }}
        name: google-cn-devsites-extension_${{ steps.get-version.outputs.result }}
        body: ${{ env.MESSAGE }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}